# Generated by Django 5.0.6 on 2024-06-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='company',
        ),
        migrations.RemoveField(
            model_name='message',
            name='office',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='office',
            name='host',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
